name: Scrolls
version: 1.3.0
description: This is scrolls done right.
author: Knaxel (Cole Philipp)
main: scrolls.ScrollsPlugin

commands:
    scrolls:
        description: The base Scrolls Command
        aliases: [scroll,sc,scr]
        permission: scrolls.command
        usage: Please use '/scrolls help' if you dont know how to use the command...